name: frost
description: A new Flutter project.

publish_to: "none"

version: 1.0.2+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  flutter_hooks: ^0.18.2+1
  flutter_animator: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: VarelaRound
      fonts:
        - asset: assets/Varela_Round/VarelaRound-Regular.ttf
          weight: 400

    - family: ComicNeue
      fonts:
        - asset: assets/Comic_Neue/ComicNeue-Bold.ttf
          weight: 700
        - asset: assets/Comic_Neue/ComicNeue-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/Comic_Neue/ComicNeue-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/Comic_Neue/ComicNeue-Light.ttf
          weight: 300
        - asset: assets/Comic_Neue/ComicNeue-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/Comic_Neue/ComicNeue-Regular.ttf
          weight: 400
