name: frost
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  flutter_hooks: ^0.18.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins/Poppins-Bold.ttf
        - asset: assets/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/Poppins/Poppins-Light.ttf
        - asset: assets/Poppins/Poppins-LightItalic.ttf
          style: italic
        - asset: assets/Poppins/Poppins-Medium.ttf
        - asset: assets/Poppins/Poppins-MediumItalic.ttf
          style: italic
        - asset: assets/Poppins/Poppins-Regular.ttf
